### ISSUE TITLE
[feature] Add filters for dealing with semconv attribute registry

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/weaver#113]
We' like a set of filters that allow us to interact with the id of an `attribute_group`.

Specifically:

- `attribute_registry_namespace`:  Converts `registry.{namespace}.{other}.{components}` to `{namespace}`
- `attribute_registry_title`:  Converts `registry.{namespace}.{other}.{components}` to `{Namespace}` (title case the namespace).
- `attribute_registry_file`:  Converts `registry.{namespace}.{other}.{components}` to `attributes-registry/{namespace}.md` (kebab-case namespace).

**Comment by lquerel** [comment]
Implemented in #136
