### ISSUE TITLE
Untie config and output folder structure

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#192]
I want to be able to generate the following code structure:

```
incubating-output/
  attributes/
    http_attributes.py
	...
  metrics
    http_metrics.py
	...
stable-output/
  attributes
    http_attributes.py
	...
  metrics
    http_metrics.py
	...
```

How I want configs to look like (to avoid duplication of weaver.yaml, have common.js, etc):

```
templates/  
  registry/ - is there a way to not have it?
    attributes.j2
    metrics.j2
	weaver.yaml
```

I'd like to be able to call weaver with extra variables to control stable vs experimental, configure excluded groups, etc.

How it currently can work:  4 weaver configs, no common shareable jinja 
```
templates/  
  registry/
    attributes/
      attributes.j2
      weaver.yaml
    incubating/attributes/
      attributes.j2
      weaver.yaml
    metrics/
      metrics.j2
      weaver.yaml
    incubating/metrics/
      metrics.j2
      weaver.yaml
```

**As a result, I have to duplicate jinja templates and weaver configs**

--------

A possible solution could be:
- output should be configurable per pattern in weaver.yaml
- have a way to pass extra context to weaver to avoid defining things in each pattern
- Nice-to-haves:
  - accept config path when running weaver
  - accept all paths to templates in weaver.yaml  patterns (../ is not accepted now)

E.g.
```yaml
  - pattern: semantic_attributes.j2
    filter: >
      .groups
      | map(select(.type == "attribute_group"))
      | map(select(.id | startswith("registry")))
      | map({ id: .id, group_id: .id | split(".") | .[1], attributes: .attributes})
      | group_by(.group_id)
      | map({ id: .[0].group_id, attributes: [.[].attributes[]] | map(select(.stability == $stability_filter)) | sort_by(.id) })
      | map(select( .id as $id | any( $excluded[]; . == $id) | not ))
      | map(select(.attributes | length > 0))
    application_mode: each
    output: $output/attributes 
```

`$exclude` is a list of namespace to exclude when generating code configurable by the caller. Same with `$stability_filter` and `output` - it should be defined by the caller.

Then I can be more flexible. E.g. I can write a config like 
```yaml
  - pattern: stable_semantic_attributes.j2
    filter: >
      .groups
      | map(select(.type == "attribute_group"))
     ... 
      | map({ id: .[0].group_id, attributes: [.[].attributes[]] | map(select(.stability == "stable")) | sort_by(.id) })
      | map(select( .id as $id | any( $excluded[]; . == $id) | not ))
    application_mode: each
    output: attributes 
  - pattern: incubating_semantic_attributes.j2
    filter: >
      .groups
      | map(select(.type == "attribute_group"))
     ... 
      | map({ id: .[0].group_id, attributes: [.[].attributes[]] | sort_by(.id) }) # no stability filter
      | map(select( .id as $id | any( $excluded[]; . == $id) | not ))
    application_mode: each
    output: _incubating/attributes 
```

Link to my current struggles trying to generate semconv in python following the existing structure.:
https://github.com/lmolkova/opentelemetry-python/commit/a7eaafcb94079937ac77dfc81dfe06b324b2c010

**Comment by lquerel** [comment]
@lmolkova can we close this GH issue with the PR #195 merged?

**Comment by lmolkova** [comment]
Yes, thank you for the fix and all the hints!
