### ISSUE TITLE
[feature] Weaver needs to update to_XYZ_case helpers to match namespacing rules in semconv

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/weaver#198]
See See https://github.com/open-telemetry/semantic-conventions/issues/1118 for context

**Comment by lquerel** [comment]
I see two options to implement this:

1. Create a `const_name` filter that by default applies the namespacing rules and generates a SCREAMING_SNAKE_CASE ID. An optional `case` parameter will allow specifying another case converter after applying the namespacing rules.
2. Add an optional parameter to all existing case converters (i.e. pascal_case, screaming_snake_case. ...) to specify whether the conversion should take into account the namespacing rules. We need to find a short name for this flag.

**Comment by jsuereth** [comment]
I think 1. isn't practical because constants vary in definition.  If `const_name` took the case type as an argument, then I think that'd be viable.

2. I like this, but it's also a bit of a footgun. I think it'd be more comfortable with `semconv_const_name(case="Pascal")`

**Comment by lquerel** [comment]
@jsuereth I'm confused :-) 
So in conclusion, you prefer option 1, but you'd like to rename `const_name` to `semconv_const_name`. Right?
