### ISSUE TITLE
Jinja code generation helpers suggestions

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#203]
Based on codegen for python with weaver https://github.com/lmolkova/opentelemetry-python/pull/2/, the following helpers (filters and/or tests) would be great to have:

1. clean up brief/note/etc - trim whitespaces, add dot at the end

```jinja
# removing a trailing dot  (keeping leading as in ".NET") is a PAIN!
{%- macro remove_trailing_dots(str) -%}
{%- if str[-1:] == '.' -%}{{ remove_trailing_dots(str[:-1]) }}{%- else -%}{{ str }}{%- endif -%}
{%- endmacro -%}

{%- macro to_docstring(str, prefix) -%}
{{remove_trailing_dots(str | trim(' \n')) | comment_with_prefix(prefix)}}
{%- endmacro %}
```

2. Print value depending on type: `"string value"`, `42`

```jinja
{%- macro print_value(type, value) -%}
{%- if type == "string" -%}"{{value}}"{%-else-%}{{value}}{%-endif-%}
{%- endmacro -%}
```

3. Add general-purpose `regex_replace`

**Comment by lquerel** [comment]
item 1 implemented by #309 
item 2 already merged
