### ISSUE TITLE
Add whitespace control in Jinja templates

### ISSUE THREAD

**Issue by lquerel** [open-telemetry/weaver#220]
Minijinja allows controlling how whitespaces are rendered in templates. See https://docs.rs/minijinja/latest/minijinja/syntax/index.html#whitespace-control.

To expose this in Weaver, we need to:
- Add a 'whitespace_control' section in 'weaver.xml'. This section should be defined in 'crates/weaver_forge/src/config.rs', specifically in the 'TargetConfig' struct. Use the 'template_syntax' section as a model.
- In the same crate's 'lib.rs', initialize the engine in the 'template_engine' method. The configuration file representation is accessible there.

**Comment by joaopgrassi** [comment]
I will try work on this, let's see how far I can get :D
