### ISSUE TITLE
Definition of the Weaver configuration at both a local and a global level

### ISSUE THREAD

**Issue by lquerel** [open-telemetry/weaver#230]
See discussion below for an updated alternative. 
See https://github.com/open-telemetry/weaver/pull/231 for details on the implementation.
---
# Proposal

Add support for a hierarchical definition of the Weaver configuration. The proposal consists of loading the configuration files in the following order:
 
- the `defaults/weaver_config` directory embedded in the Weaver binary. 
- the `$HOME/.weaver/weaver.yaml` directory, 
- the parent directory (i.e., the directory containing all targets), 
- and finally the target directory, 
 
A local definition will override any corresponding definition in the parent directory (shared across all targets), which itself can override the corresponding entry in the home directory (defined per user), and finally, the Weaver application binary (defined by Weaver authors). To summarize, this hierarchical structure will allow for configuration at the target level, across all targets, at the user level, and even reuse of configurations defined within the Weaver application binary.

> This proposal is introduced, among other things, to support #211.

# Why

There has been a past need to define configurations or definitions common to multiple languages, multiple teams, etc. This is the main reason for implementing a mechanism that allows for a hierarchical and override mechanism within Weaver’s configuration system.

The current organization (i.e., templates/<target>/) is more of a default organization that seemed logical at the time. The initial idea was to easily list the available targets for users and offer a hierarchical organization to share certain configuration elements (e.g., acronyms or whitespace control shared between multiple targets). 

# Alternative

If the need to list all the available targets is not important for the community, we could use a different approach based on two parameters:

- `--templates` to point to the directory containing the templates to apply.
- `--config` to list one or several `weaver.yaml` files that will be applied in the specified order. By default, this parameter could retrieve the config files based on the list of paths mentioned in the proposal above (minus the parent directory, which will no longer be valid in this alternative).

**Comment by lquerel** [comment]
# Discussion

After some reflection, I propose the following approach, which I believe will be more aligned with how Weaver is currently used in the context of code generation. Typically, Weaver is used on a GitHub repository dedicated to a specific language. In this context, the concept of `target` is no longer relevant since there will generally be only one target in this repository (this might not be true for entreprises using Weaver).

To recap, the current approach relies on two parameters: `--templates` and `--target`. `--templates` points to the root directory containing the targets for the semconv registries, or in the future, the targets for schemas (app telemetry schema). When this parameter is not set, it defaults to `templates/`. The `--target` parameter is mandatory and targets the templates to be resolved with the following logic:

- When the command `weaver registry generate --target rust` is called, the templates that will be generated are loaded from `templates/registry/rust`.
- When the command `weaver schema generate --target rust` is called, the templates that will be generated are loaded from `templates/schema/rust`.

Indeed, this approach, when applied to a repository dedicated to creating a client SDK for a single language, is somewhat overkill. I agree it's a bad UX.

# New Proposal

This new proposal can be summarized as follows:
- `--templates` now points directly to the directory containing the templates to be generated. By default, this directory will be `templates/`.
- `--target` is no longer used and becomes optional.
- `--config` is a new optional parameter (n-ary) that allows listing the weaver.yaml files to load before applying the template generation. Multiple configuration files can be specified, and their order is important because the override mechanism will be applied in the order of the files' appearance (i.e., file n overrides file n-1, etc.). When the `--config` parameter is not specified, it will automatically be set as follows:
  - the defaults/weaver_config directory embedded in the Weaver binary.
  - the $HOME/.weaver/weaver.yaml directory,
  - all weaver.yaml files defined from the root to the effective path specified by the `--templates` parameter. This approach is used, for example, by the `cargo` command to load and resolve `Cargo.toml` files.

In terms of UX, the authors of a repository will generally not need to specify anything if they place their templates directly in the `templates/` directory. If they wish to implement variations for document or code generation, they can still define their own template organization and use the `--templates` parameter. If they do not want the default Weaver configuration resolution mechanism, they can then use the `--config` parameter.

> Note: Although there are probably very few Weaver users at the moment, I propose the following transition, which remains compatible with the existing setup for a yet-to-be-defined period. The new approach is only applied when the `--target` parameter is not specified. The `--config` parameter can be applied to both approaches. I also propose adding a "deprecated" note indicating that the target concept will be removed in the near future (exact timeline to be determined).

**Comment by jsuereth** [comment]
So I'm reading through this and haven't had time to digest, so apologies if this is half formed.

Some quick thoughts.

1. I think in the long run, weaver should be providing "codegen packages".  That is bundled config, for many languages, that users can use and leverage/reference.  Possibly with release cadence and such similar to a docker image or cargo package.  Effectively we need way to create codegen and bump it, and I don't see weaver adopted *past otel core* without having a good default for codgen/docgen.  I *do not think* this codegen/docgen we provide by default will be semconv library, but something more targeted at non-otel libraries.
2. The current proposal w/ config is confusing in one sense:  Config defines the tempalte to use in a JQ expression.   I think that config belongs near the templates.  I think merging everythign together in a unified model is ok, but think about the use case for each location of config and maybe tune/optimise these.
