### ISSUE TITLE
Change what prefix means in the schema

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#263]
Depends on https://github.com/open-telemetry/semantic-conventions/issues/1292 and https://github.com/open-telemetry/semantic-conventions/pull/1293

Once we migrate semaconv tooling to  weaver, we can reconsider usage prefix:

- prefix could be a property that's used to validate that all attributes defined in scope of group have this prefix
  - it could be required to embed things and might be optional in other cases
- prefix is removed and only used when embedding things.

**Comment by lmolkova** [comment]
blocked on embedding https://github.com/open-telemetry/semantic-conventions/issues/1264

**Comment by jsuereth** [comment]
Let's remove prefix form weaver in `--future` mode.
