### ISSUE TITLE
Publish docker image with for `arm64` platform 

### ISSUE THREAD

**Issue by jack-berg** [open-telemetry/weaver#345]
While incorporating weaver into `semantic-conventions-java`, we discovered that the weaver docker image doesn't have multi platform support, so running it in arm64 requires this extra argument. 

> Apparently the `otel/weaver` image doesn't publish for `arm64` platform yet. 

```suggestion
        "--rm",
        "--platform=linux/x86_64",
```

_Originally posted by @jack-berg in https://github.com/open-telemetry/semantic-conventions-java/pull/70#discussion_r1731439609_

**Comment by jsuereth** [comment]
This looks to be not too hard using docker-provided actions: https://docs.docker.com/build/ci/github-actions/multi-platform/

**Comment by jsuereth** [comment]
So while I got a build working - It looks like we DON'T want to pay the rust compiler cost through QEMU emulation.

I'll lookinto updating the PR for this guidance: https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners
