### ISSUE TITLE
Comment line wrapping

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/weaver#416]
The current Go tooling uses the `wordwrap` jinja macro to ensure long comment lines are wrapped:

https://github.com/open-telemetry/opentelemetry-go/blob/81b2a33e1bbc57ef8f401e5ee7aaa9bc6b7ac772/semconv/template.j2#L138

How can this same wrapping be achieved with weaver?

From testing it seems the `wordwrap` macro does not exists.

**Comment by lquerel** [comment]
Not yet supported. Duplicate of #364

**Comment by MrAlias** [comment]
Closing as duplicate.
