### ISSUE TITLE
No trailing spaces in comments

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/weaver#417]
The comment formatter allows you to specify a prefix for comments. Setting this to something like `// ` results in the following when formatting "foo\n\nbar\n":

```go
// foo
// 
// bar
```

The middle line has a trailing space from the specified prefix.

How can I not have this? For example:

```go
// foo
//
// bar
```

Is there a way to have a prefix for lines that contain characters and another for empty lines?

**Comment by lquerel** [comment]
I see. Currently, there is no way to do that, but I believe we should extend the semantics of the trim configuration parameter to also trim empty comment lines on the right.
