### ISSUE TITLE
`registry update-markdown` command fails with warning, but returns 0

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#434]
Try  https://github.com/open-telemetry/semantic-conventions/commit/5261f966ab4e4102eb454d19d21edc9c46a565a5:

```
/mnt/c/repo/semantic-conventions$ make table-check
docker run --rm \
        --mount 'type=bind,source=/mnt/c/repo/semantic-conventions/templates,target=/home/weaver/templates,readonly' \
        --mount 'type=bind,source=/mnt/c/repo/semantic-conventions/model,target=/home/weaver/source,readonly' \
        --mount 'type=bind,source=/mnt/c/repo/semantic-conventions/docs,target=/home/weaver/target,readonly' \
        otel/weaver:v0.10.0 registry update-markdown \
        --registry=/home/weaver/source \
        --attribute-registry-base-url=/docs/attributes-registry \
        --templates=/home/weaver/templates \
        --target=markdown \
        --dry-run \
        /home/weaver/target

Diagnostic report:

  ⚠ The attribute `process.executable.build_id.profiling` in the group
  │ `registry.process.deprecated` contains an example that will be considered
  │ invalid in the future. This attribute is a string but it does not contain
  │ any examples..
  │ Provenance: "/home/weaver/source/process/deprecated/registry-
  │ deprecated.yaml"



Total execution time: 0.198580721s
/mnt/c/repo/semantic-conventions$ echo $?
0
```

We should either convert this warning into error (it's fine for anything new that we add) or continue the execution

**Comment by lquerel** [comment]
For any new version of the registry, the plan is to use `--future` to convert warnings into errors (resulting in an exit code of 1). Without `--future`, Weaver will emit warnings for this type of check to maintain compatibility with older registry versions.

Please close the issue if my response satisfies you. Thank you.

**Comment by lmolkova** [comment]
I switched to `future` in semconv. The problem that it does not work correctly without a warning - warning stops semconv generation when it occurs but result in 0 code. 

I.e. if I have a warning, I can't generate markdown

**Comment by lmolkova** [comment]
compare the output above with the real md update - the first one didn't update anything, the one below updated everything

```log
neskazu@neskazu:/mnt/c/repo/semantic-conventions$ make table-check
docker run --rm \
        --mount 'type=bind,source=/mnt/c/repo/semantic-conventions/templates,target=/home/weaver/templates,readonly' \
        --mount 'type=bind,source=/mnt/c/repo/semantic-conventions/model,target=/home/weaver/source,readonly' \
        --mount 'type=bind,source=/mnt/c/repo/semantic-conventions/docs,target=/home/weaver/target,readonly' \
        otel/weaver:v0.10.0 registry update-markdown \
        --registry=/home/weaver/source \
        --attribute-registry-base-url=/docs/attributes-registry \
        --templates=/home/weaver/templates \
        --target=markdown \
        --dry-run \
        /home/weaver/target
✔ Registry resolved successfully
ℹ Validating: $/home/weaver/target/attributes-registry/android.md
ℹ Validating: $/home/weaver/target/attributes-registry/artifact.md
ℹ Validating: $/home/weaver/target/attributes-registry/aspnetcore.md
ℹ Validating: $/home/weaver/target/attributes-registry/aws.md
ℹ Validating: $/home/weaver/target/attributes-registry/azure.md
ℹ Validating: $/home/weaver/target/attributes-registry/browser.md
ℹ Validating: $/home/weaver/target/attributes-registry/cicd.md
......
ℹ Validating: $/home/weaver/target/url/url.md

Total execution time: 26.20920886s
```

**Comment by lquerel** [comment]
Alright, sorry about that; I understand now. I’ll make the following changes. Let me know if you’re okay with this:

- If `--future` is present in the arguments, no generation will occur if there are warnings or errors, and the command will return a code of 1.
- If `--future` is not present in the arguments, the markdown generation will proceed only if there are no errors. In this case, warnings will be displayed (if any), markdown will be generated, and the command will return 0. If at least one error is detected, errors (and warnings, if present) will be displayed, no generation will occur, and the command will return a code of 1.

The other commands already work like this. This oversight must have happened when I introduced `--future`.
