### ISSUE TITLE
Support stability definitions from OTEP 232

### ISSUE THREAD

**Issue by lmolkova** [open-telemetry/weaver#502]
Part of https://github.com/open-telemetry/semantic-conventions/issues/1096

We need to include new maturity levels formally defined in [OTEP 232](https://github.com/open-telemetry/oteps/blob/main/text/0232-maturity-of-otel.md):

- Development - new one that replaces `experimental`. We should keep supporting `experimental`, but treat it as `developement`
- Alpha - new 
- Beta - new 
- Release Candidate - new 
- Stable - no change
- Deprecated - no change (not a stability level from the semconv schema perspective)
- Unmaintained - don't add for now

This would mean:
- extending the [stability enum](https://github.com/open-telemetry/weaver/blob/c7e27b243f09ada21e67d12226c03d8b0ca3ad76/crates/weaver_semconv/src/stability.rs#L12) to cover new members
- update [`is_experimental` filter](https://github.com/open-telemetry/weaver/blob/c7e27b243f09ada21e67d12226c03d8b0ca3ad76/crates/weaver_forge/src/extensions/otel.rs#L283) to cover all maturity levels (i.e. return `true` for all levels except `stable`)
- update [schema definition](https://github.com/open-telemetry/weaver/blob/c7e27b243f09ada21e67d12226c03d8b0ca3ad76/schemas/semconv.schema.json#L531) to list all new possible values

**Comment by jerbly** [comment]
@lmolkova - I can do this one. Set me as the assignee if you like??

**Comment by lmolkova** [comment]
@jerbly thank you, really appreciate your help!

**Comment by jerbly** [comment]
Made #504 - hopefully this is what you had in mind. 🤞
