### ISSUE TITLE
Odd behavior when specifying *only net new* `templates` in weaver.yaml

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/weaver#85]
I added 
```
templates:
  - ... my addition...
```

And noticed that instead of reading *my* template directory files (in the test harness), the global ones were selected instead.  This could be because I was running `cargo test --all`, but it definitely caused failures.

Making a note here to investigate further.

**Comment by lquerel** [comment]
This has been fixed. Unfortunately I don't remember this PR #.
