### ISSUE TITLE
Weaver_forge does not output minijinja debug information in release build.

### ISSUE THREAD

**Issue by jsuereth** [open-telemetry/weaver#98]
When building in release mode, the JINJA failure messages are not output.  These are helpful as they generally include:

- A pointer to the line/character of the template that fails
- A JSON dump of the current context being used to render the template

See #97

**Comment by lquerel** [comment]
IIRC, this was fixed a long time ago. We should try to re-enable the build in release mode in the Docker image, and if it works, we can close this issue.

**Comment by jsuereth** [comment]
This appears to be fixed!
